### PR TITLE
Update simpleindex.html

### PR DESCRIPTION
**Pull request by frankie-eo**
Fixed syntax error

### CODE REVIEW

**Comment by alanjones2** [comment]
I'm sorry but this is not a syntax error. The data passed is a string so the enclosing quotes are not required.

**Comment by frankie-eo** [comment]
Fair enough. I kept getting a syntax error even with json.dumps() in place and it only worked for me this way. Might be specific to my setup.

**Comment by alanjones2** [comment]
You will get a syntax error if your editor or IDE is treating the file as HTML (and enclosing the offending part in quotes hides that 'error'). If you change the file type from HTML to Jinja, then the error will go away. (Or you could simply ignore it!)

Here's the bottom right corner of my VSCode window:

image

If you are using VSCode, the file type displayed here will probably be 'HTML'. But if you click on the file type you'll get a drop-down menu of other types to choose from - choose 'Jinja'.

**Comment by frankie-eo** [comment]
Ah, I see.  Thanks!

**Pull request closed without merging**
